### ISSUE TITLE
The ID field in the status resource has the wrong data type

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#1]
Location: Section 4.3.1
![image](https://user-images.githubusercontent.com/2951827/31456296-4ddc11dc-ae87-11e7-93ab-bc05d667ab70.png)

The data type for the ID field in the status resource is wrong. It is set to a string and then in the description it says that it is an "identifier".  This is not how we have done this elsewhere.  The type needs to be changed from string to identifier. A suggestion has been made in the 2.1 document to fix this.

**Comment by MarkDavidson** [comment]
Recommendation: Accept Change

**Comment by jordan2175** [comment]
Document has been updated and changes accepted.
