### ISSUE TITLE
The example for the get_objects endpoint is wrong

### ISSUE THREAD

**Issue by rpiazza** [oasis-tcs/cti-taxii2#10]
Section 5.5

The response uses old syntax for the bundle:

![image](https://user-images.githubusercontent.com/2951827/31457141-de91ceb8-ae89-11e7-975e-c7850315557b.png)

```
{  
  "type": "bundle",
  ...,
  "indicators": [
    {
      "type": "indicator",
      "id": "indicator--252c7c11-daf2-42bd-843b-be65edca9f61",
      ...,
    }
  ]
}
```
There is only one property now to store the SDOs and SROs - `objects`

**Comment by MarkDavidson** [comment]
Recommendation: Accept proposed text

**Comment by jordan2175** [comment]
Changes made to 2.1 document.

**Comment by jordan2175** [comment]
This was also changed in 3.7
