### ISSUE TITLE
What is the purpose of Discovery API roots having different domains in the list of api_roots ?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-taxii2#100]
Trying to understand the usage of api_roots having various domain names.

edit: I am guessing it is assumed that a discovery api is being provided by a super-system that is not necessarily a taxii system?  Such as Consul providing a discovery all of taxii systems and their urls?

**Comment by jordan2175** [comment]
The API Roots represent a grouping of collections of data, permissions, and users. You can think of an API Root as an instance of the TAXII API that might be tied to a specific trust group.  So one TAXII server can support multiple trust groups.  A Discovery Resource is how a TAXII servers tells TAXII clients about API Roots that it knows about (either hosted on the same system or on other system.  

If this does not answer your question, please reopen the ticked or reach out to me directly.

**Comment by StephenOTT** [comment]
yes your explanation makes sense.

I was looking at the 2.0 docs are defining the data model as a direct 1-1 similar to the STIX docs.  But ya there are some additional fields that need to be added for actual data modelling.

thanks
