### ISSUE TITLE
API Root Resource does not define the URL of the resource?

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-taxii2#101]
In the docs, the API Root resource shows a data model of title, description, versions, and max_content_length, but does not dictate URL.  The URL is needed based on accessor url of the root info such as "https://example.com/api1/".  where /api1 is the url to that specific root.

What is the history for the omission of this property in the actual object?

**Comment by jordan2175** [comment]
I am not sure what you mean.  If a client is communicating with an API Root, then the client will know the URL that it is talking to.  So yes, there is no property called "self" that self advertises the resource.  The discovery resource however does contain a list of fully qualified URIs.  

Does this answer your question?

**Comment by StephenOTT** [comment]
This is similar to https://github.com/oasis-tcs/cti-taxii2/issues/100

The confusion here was expecting the "data model" description being a 1-1 to the base/minimum fields needed to implement a data model.  Additional fields are needed to do actual data storage/modelling.

Thanks for the quick followup! 👍
