### ISSUE TITLE
Typo in url prop of section 5.4

### ISSUE THREAD

**Issue by StephenOTT** [oasis-tcs/cti-taxii2#102]
url prop description reads `/<api-root>/Collections/<id>/objects/`

should read `/<api-root>/collections/<id>/objects/`

Has typo with the capitalization of the `C` in collections

**Comment by jordan2175** [comment]
I can not find this anywhere in the live version of the document, found at the following URL.  Please specify a section number and location of where this is located.  My guess is that this was already fixed for the soon to be released TAXII 2.1.  If this is still valid, and found in the document listed below, please reopen this issue.

https://docs.google.com/document/d/1EsiWY7TGqt9yH6QUXv4c-opXSr3wR0TDMt8Q0yJjpoo/edit#heading=h.4do73o99e2l7

**Comment by StephenOTT** [comment]
yes looks fixed.

thanks
