### ISSUE TITLE
Add clarifying text around can_read and can_write attributes of Collection

### ISSUE THREAD

**Issue by gtback** [oasis-tcs/cti-taxii2#12]
In the table in section 5.2.1:

* For `can_read`, add `If true, users are allowed to access the Get Objects, Get an Object, or Get Object Manifests endpoints for this Collection. If false, users are not allowed to access these endpoints.`
* For `can_write`, add `If true, users are allowed to access the Add Objects endpoint for this Collection. If false, users are not allowed to access this endpoint.`

In sections 5.3, 5.5, and 5.6 add `If the Collection specifies can_read as false, this Endpoint SHOULD return a HTTP 403 error. ` (or maybe MUST)

In section 5.4, add `If the Collection specifies can_write as false, this Endpoint SHOULD return a HTTP 403 error. ` 

In all of the above, we may want to add "for a particular user", since I believe different users can have different rights to the same Collection.

**Comment by MarkDavidson** [comment]
Recommendation: Accept proposed text

**Comment by jordan2175** [comment]
Accepted changes in 2.1 document. There is still an open question about making it a MUST vs a SHOULD.  We should open a separate issue for that.

**Comment by jordan2175** [comment]
We changed the text to be:

> for a particular client, this Endpoint MUST return an HTTP 401 (Unauthorized),  HTTP 403 (Forbidden), or HTTP 404 (Not Found) error.

**Comment by jordan2175** [comment]
Changed in 5.3, 5.4, 5.5, 5.6
