### ISSUE TITLE
Add text about TLS 1.3 0-rtt

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#17]
We need to add clarifying text to TAXII 2.1 about not using TLS 1.3 0-rtt.  I would suggest we use the following text.  "Implementations MUST NOT use TLS 1.3 0-rtt for TAXII".  The reason for this is the known security implications with 0-rtt with REST based protocols. These are well documented in the IETF TLS 1.3 document.

**Comment by jordan2175** [comment]
Added suggested text in section 8.2.2

**Comment by MarkDavidson** [comment]
Can a link be provided to the appropriate document/section?
