### ISSUE TITLE
The X headers are not clear about which date

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#19]
In the spec we defined two headers `X-TAXII-Date-Added-First` and `X-TAXII-Date-Added-Last`.  My question is, should this be the time the object was added to the server or the time it was added to the collection that you are pulling from...  When I wrote this originally, I was thinking about the time it was added to the server.  But now that I have working code and am trying to implement this feature, there is a difference between when an object is added to a server and when it was put in a collection. Some times these will be the same time, other times, an object may be added to a collection after some sort of analysis, which means it was already in the server.

**Comment by JasonKeirstead** [comment]
My vote is to make these values for the collection.

I can't think of a use case to have them for the server.

**Comment by jordan2175** [comment]
Added suggested text in section 3.2 but it needs help. 
Fixed text in 5.6.1.

**Comment by jordan2175** [comment]
I no longer think this is a good idea.

**Comment by jordan2175** [comment]
We changed the text to be more implementation independent.
