### ISSUE TITLE
Version key word 'all' should not be allowed when using multiple version parameters

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#26]
Section 3.5.1

The spec does not currently say anything about using the "all" keyword in addition to other keywords.  The "all" keyword should be restricted from multiple version selectors...  Examples:

?match[version]=all = OKAY
?match[version]=last,first = OKAY
?match[version]=last,all,first === THIS SHOULD BE ILLEGAL

**Comment by allant0** [comment]
i dont think this is really a breaking change. No one would implement all in this way so I think what you suggest is really just making the spec clearer and not 'breaking' in reality.

**Comment by jordan2175** [comment]
This was discussed on the working call on 2018-01-23 and no one objected to make this normative text change.  The proposed text was "the all key word MUST NOT be used with any other version key word or version parameter". The following people were on the working call: Bret Jordan, Trey Darley, John-Mark Gurney, Sarah Kelley, Chris Ricard, Dave Lemire, Jason Keirstead, Nicholas Hayden, Richard Struse, Sunil Ravipati. Suggesting was made in section 3.5.1

**Comment by MarkDavidson** [comment]
Clarifying text might still be useful, but the version parameter isn't specified as a list, so this situation isn't possible.

**Comment by jordan2175** [comment]
All parameters can be lists by using a comma.

**Comment by jordan2175** [comment]
Text was added to 3.4.1 in the version row, "all" bullet. The whole text now reads:

> all - requests all versions of an object. The all keyword MUST NOT be used with any other version parameters.
