### ISSUE TITLE
Returning the number of results is not explicitly clear

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#42]
In the 2.0 specification we talk about the server returning the total number of results.  It is felt that this is not super clear.  Does this mean the number of records in the collection or the number of records that match a certain query.  All it says is "in a result set".  If we keep this in our new pagination style, when that is designed, it should probably be made to be optional and it should probably be the total number of objects / items in the collection, not the number of objects that match the current filtered query.

**Comment by MarkDavidson** [comment]
Can this issue be clarified? I'm not clear on what it means. Perhaps something like "Text describing number of results is unclear", and a link to or quotation of the unclear text.

**Comment by jordan2175** [comment]
We discussed this on the working call on 2018-02-20 with the following 15 TC members (Bret Jordan, Trey Darley, Chris Ricard, Christian Hunt, Dan Dye, Dave Lemire, Drew Varner, Efrain Ortiz, Gary Katz, Jane Ginn, John-Mark Gurney, John Wunder, Nicholas Hayden, Paul Patrick, Rich Piazza). The consensus on the call was that it probably should be the number of objects that match the query or filter that was provided.  However, we need to do some more investigation on this once we redo our pagination style. I think if we do keep this, with our pagination changes, then we should probably make it optional for the server to implement.

**Comment by jordan2175** [comment]
Based on the current discussions about pagination, this may not actually be an issue going forward.

**Comment by jordan2175** [comment]
The pagination style we have implemented in TAXII 2.1 does not use this feature.  So this can be closed.
