### ISSUE TITLE
Add Collections to X- Header list

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#44]
We provide two headers useful for pagination outside of the standard way:

* `X-TAXII-Date-Added-First`
* `X-TAXII-Date-Added-Last`

They are required for:

* `GET <api-root>/collections/objects/`
* `GET <api-root>/collections/manifest/`

They should also be required for `GET /<api-root>/collections/`, since it also requires pagination support.

**Comment by jordan2175** [comment]
So the first and last dates would just be the same for the case of a collection though right?

**Comment by varnerac** [comment]
After the Slack discussions on pagination, I'm not convinced this is a good idea. Instead, I think pagination of Collections should be my the Collection id as @MarkDavidson suggested. Time-based pagination alone is inadequate.

**Comment by varnerac** [comment]
OBE. No point in fixing his given `added_after` pagination in 2.1
