### ISSUE TITLE
Make Error responses optional

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#47]
# Issue

TAXII 2.x Error Messages take an opinionated view of where the TAXII server sits in an enterprise. The standard mandates TAXII-specific JSON responses to common HTTP errors:

> TAXII responses with an HTTP error code (400-series and 500-series status codes, defined by sections 6.5 and 6.6 of [RFC7231]) that permit a response body (i.e. are not in response to a HEAD request) MUST contain an `error`  message (see section 3.6.1) in the response body.

This raises a number of issues for implementers. Services often sit behind load balancers and gateways.

### Scenario 1 - Authentication Gateway

I have a security gateway that handles authentication via basic auth or client certificates. I place my TAXII server behind this gateway. If authentication/authorization fails in the gateway with an HTTP 401, I have to intercept the auth gateway's response and lift it to JSON.

### Scenario 2 - Libraries

A number of enterprises and vendors have software components for auth. Instead of dropping them in a stack, I have to do something similar to Scenario 1 and drop another piece of middleware between the auth layer and the client in my stack to lift the vanilla 401 to JSON.

### Scenario 3 - General Purpose Gateways

Load balancers and tools like web application firewalls will process requests before they hit TAXII for any sizable deployment. They are likely to handle the following HTTP codes in sections 6.5 and 6.6 of RFC 7231:

* 400 Bad Request
* 404 Not Found
* 405 Method Not Allowed
* 408 Request Timeout
* 413 Payload Too Large
* 414 URI Too Long
* 503 Service Unavailable
* 504 Gateway Timeout
* 505 HTTP Version Not Supported

They won't respond with TAXII-specific JSON

## Limited Value

There is limited value in many of the standard `error` fields. `http_status` is already in the response. I don't need a `title` on a 404, because this is machine-to-machine communication. You can believe that a request to `/foo/collections/170f24af-c685-411d-bd2a-f45248adb245/` is "Collection not found". There is no way to know. It could be "not found" on the Get API Root Information endpoint where the API Root is `/foo/collections/170f24af-c685-411d-bd2a-f45248adb245/`. The same goes for invalid parameters. You may _think_ that `/foo/collections/170f24af-c685-411d-bd2a-notarealuuid/` is an invalid UUID parameter to a Collection, but it can also be a valid API Root. If you drop some crafted paths in a deterministic routing engine like Yesod's, you'll see how you can abuse nondeterminism in TAXII's API Root support.

# Recommendation

> TAXII responses with an HTTP error code that permits a response body (i.e. are not in response to a HEAD request) MAY contain an `error`  message (see section 3.6.1) in the response body.

I have intentionally removed the HTTP 1.1 reference because I'd like to see optional HTTP2 support in 2.1.

**Comment by varnerac** [comment]
I may have been wrong to pull the HTTP 1.1 reference. HTTP/2 defers a lot of guidance to the HTTP 1.1 spec.

**Comment by johnwunder** [comment]
This seems reasonable, though I could also see an argument for it being a SHOULD.

**Comment by varnerac** [comment]
I feel like any significant TAXII Server is going to have to sit behind a load balancer. It’ll be really difficult to handle the LB’s responses as JSON, especially in the Cloud. That’s why I’m hesitant to even use SHOULD.

**Comment by jordan2175** [comment]
This is in section 3.1.  The text we are looking to change is:

> TAXII responses with an HTTP error code (400-series and 500-series status codes, defined by sections 6.5 and 6.6 of [RFC7231]) that permit a response body (i.e. are not in response to a HEAD request) MUST contain an error message (see section 3.5.1) in the response body.

And we are looking to change the last MUST to be either a SHOULD or a MAY.

**Comment by jordan2175** [comment]
Does this also impact our Status Resource that is sent back with a 202 (Accepted) ?

**Comment by varnerac** [comment]
No. It's not an error.

**Comment by jordan2175** [comment]
This changes was made in Section 3.1

Drew and I discussed this, and it seems like a MAY is the right way to go, since load balancers and cloud systems may need to do creative things with routing the error messages. The new text now says:

> TAXII responses with an HTTP error code (400-series and 500-series status codes, defined by sections 6.5 and 6.6 of [RFC7231]) that permit a response body (i.e. are not in response to a HEAD request) MAY contain an error message (see section 3.5.1) in the response body.
