### ISSUE TITLE
API Root TAXII Version does not match Media Type Version

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#48]
In the API Root resource we advertise the TAXII version as "taxii-2.0" or "taxii-2.1".  However, in the media negotiation we do "version=2.0".  These should probably be the same or should be done in such a way to make it more clear.

**Comment by johnwunder** [comment]
Agree. I believe this needs to be resolved via #49.

**Comment by jordan2175** [comment]
This was resolved in WD01
