### ISSUE TITLE
Section 3.3 still talks about an object search endpoint

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#51]
In section 3.3 we forgot to remove the paragraph about the object search endpoint back when we removed that endpoint when we were finalizing TAXII 2.0.  Since we no longer have an object search endpoint, I suggest that we remove this paragraph.  The text that we should remove is:

> For the Object Search Endpoint, objects MUST be sorted in ascending order by the date the object first appeared in object search (i.e., the added date). If an object would appear multiple times, all appearances after the first appearance MUST be omitted from the result. That is, if an object would have appeared first in the list and again halfway down, only the first entry should be present in the result.

**Comment by jordan2175** [comment]
The proposal I sent to the email list is to just remove this paragraph as it is left over from when we had an Object Search endpoint.  Since that endpoint does not exist, I believe we should just remove the text that talks about it.  I made a call for objections to the list.

**Comment by JasonKeirstead** [comment]
Instead of removing it should it be updated to talk about Filtering?

**Comment by jordan2175** [comment]
@JasonKeirstead filtering is talked about in the very next section in the document. Are you looking for something besides what is already there?

**Comment by JasonKeirstead** [comment]
Never mind, I guess it makes no sense.

I agree, +1 lets turf it.

**Comment by johnwunder** [comment]
+1

**Comment by jordan2175** [comment]
The following text has been removed from section 3.3 Sorting:

> For the Object Search Endpoint, objects MUST be sorted in ascending order by the date the object first appeared in object search (i.e., the added date). If an object would appear multiple times, all appearances after the first appearance MUST be omitted from the result. That is, if an object would have appeared first in the list and again halfway down, only the first entry should be present in the result.
