### ISSUE TITLE
Link to Google Docs index

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#55]
There is an index of Google docs here: https://docs.google.com/document/d/1yvqWaPPnPW-2NiVCLqzRszcx91ffMowfT5MmE9Nsy_w/edit

It'd be handy to have it in the README since docs there are relevant to issues in this repository.

**Comment by jordan2175** [comment]
I added this to CTI TAXII Home Page on Kavi. The README for this Github is boiler plate from OASIS and I doubt we can add anything there.
