### ISSUE TITLE
Make api-root versions optional or remove it

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#57]
Proposed changes in 2.1 to "​1.5.7​ Content Negotiation" seek to add a `version` parameter to the STIX and TAXII media types. If these changes go in, we should make the `versions` field in `api-root` optional or just get rid of it.

The `version` parameter in the media types allows us to negotiate content via [RFC 7231 Content Negotiation](https://tools.ietf.org/html/rfc7231#section-5.3)

The versions strings used now in `api-root`, like `taxii-2.1` will duplicate the corresponding information in the media type that can be negotiated through `Accept` headers.

**Comment by jordan2175** [comment]
We will change this text to say that the parameter MUST match the media type text.

**Comment by jordan2175** [comment]
The text now reads:

> The list of TAXII versions that this API Root is compatible with. The values listed in this property MUST match the media types defined in Section 1.5.8.1 and MUST include the optional version parameter. A value of application/taxii+json; version=2.1 MUST be included in this list to indicate conformance with this specification.
