### ISSUE TITLE
Clarify scope of STIX objects in TAXII

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#59]
We should clarify the scope of STIX objects stored in a Collection.

The "Add Objects" endpoint on Collections says:

> This Endpoint adds objects to a Collection.

By lowercase _objects_, I assume this can mean a STIX 2 Object, a version of a STIX 2 Object (which is an object but not an Object) or some non-STIX object.

Are we really adding STIX objects to a Collection or are they added to the Server?

The way I understand TAXII 2, for the most part, is that TAXII 2 Collections are bookkeeping around a STIX 2 store. STIX 2 objects are global. This means there is a many-to-many relationship between STIX objects and Collections.

E.g. STIX Object 1 is in two collections. If I push a new version in Collection 1, that new version is also available to Collection 2. The same goes with revocation.

However, the structure of the REST requests and the wording in the spec directly contradict my understanding. "objects" are added to a Collection, not in a globally-scoped STIX store accessible to the server.

Is my understanding of the scope of STIX objects and how they are stored in TAXII incorrect?

**Comment by jordan2175** [comment]
Yes this is correct, please help fix the specification language and make suggestions in any place where you find that it is wrong.

**Comment by johnwunder** [comment]
It seems like we need a lot of clarifying language about this because I was actually thinking about it the other way (that if you update an object in one collection the update is not automatically made to the other collection). I don't think I have a strong preference for which it should be (I can see arguments in both directions) but it's obviously not clear enough as-is.

**Comment by varnerac** [comment]
I agree it’s unclear. I initially thought the same way as you. Also, for non-STIX collections, where they don’t have a UUID generated by author, they may not have a universal scope and become one-to-many.

**Comment by varnerac** [comment]
From Allan:

> An object version is not tied to where it is stored in one or more collection. A version of object is a historical tracking of changes to that object whether its in 1 collection or 10 collections.

> Most systems will ask for the most recent version of an object and not care to ask for different versions. They will ask for 'the' object and then if they care about the version then they will handle the different notifications/delta UI ...etc updates that they want to do.

> Most publishers will post the latest version of the object only to the taxii server. They wont care whether the taxii server had previous versions and would expect that most systems pulling those objects will get the latest one. If a taxii server keeps multiple versions of an object in a collection then thats a choice of the server. But frankly I think it overcomplicates the server and unnecessary as historical context is not something the taxii server should have to deal with. Thats a product problem and use case specific.

**Comment by varnerac** [comment]
I agree that TAXII servers can choose to store only the latest version. When TAXII servers store multiple versions, the query results shouldn't vary by server implementation for the same data. Object versions add complexity, but I think we have to deal with them at the spec level, even though implementations may bot store multiple versions. All I care is that we deal with them in the same manner.

It seems like you're advocating for Object to Collection mapping, instead of Object version to Collection mapping.

I just want consensus on the correct mapping.  Otherwise, things won't interoperate.

**Comment by jordan2175** [comment]
My take on this is a collection will have all versions of an object.  Meaning, the STIX ID is mapped to the collection.  If that STIX ID is mapped to collections A and B then if you update a version of the object in collection A that version will automatically propagate to collection B.  For those that want to do versions per collection be super careful for what you ask for.  You may want to write the book keeping code first, to prove to yourself that it is a bad idea.

**Comment by varnerac** [comment]
I think that’s valid. Some days I think that’s the right answer.
