### ISSUE TITLE
Clarify URL for api endpoint

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#62]
The table in section 3.1 "Endpoints" shows how to form endpoint URLs given an API Root URL (`<api-root>`)

For example.

`<api-root>/collections/`
`<api-root>/collections/<id>/objects/`

so far, so good. We can deduce from this that API Root URLs don't end in `/`.

```https://foo.com/bar//collections/``` would be a goofy URL.

However, 

```<api-root>``` is listed as the URL for the `api` endpoint

Does this mean that every URL in TAXII 2.x except for `api` ends in `/`? I feel like this is an oversight and the pattern for the `api` endpoint should be:

```<api-root>/```

I propose making this change in the spec.

**Comment by jordan2175** [comment]
This was fixed as part of editorial oversight.
