### ISSUE TITLE
Expand Status Resource to include message for pending and successes statuses

### ISSUE THREAD

**Issue by marlontaylor** [oasis-tcs/cti-taxii2#65]
The Status Resource provides detailed information for failures via a list of status-failure type which contains:
- **_id_** - The identifier of the object that failed to be created. For STIX objects the id MUST be the STIX Object id. For object types that do not have their own identifier, the server MAY use any value as the id.
- **_message_** - A message indicating why the object failed to be created.

While the successes and pending statuses only contain a list of stings:
- **_string_** - For STIX objects the STIX ID MUST be used here. For object types that do not have their own identifier, the server MAY use any value as the id.

successes and pending should include the ability to provide a message.

## Options:

**Backward Compatible** - expand the Status Response to include two optional keys (pending_responses and success_responses) which will contain a list of status-failure to provide detailed information for successes and pending statuses.
- the next major version of TAXII will implement this change and depreciate the list of strings

**Non-Backward Compatible** - update the current successes and pending to use `status-failure`.

**Comment by gtback** [comment]
For clarity, if we do use the non-backward-compatible option, we might want to rename the `status-failure` structure to something that's not specific to failures.

**Comment by jordan2175** [comment]
We discussed this on the working call on 2018-05-15 and the consensus was to accept this change, however, there was not a decision on how this should be done.  The editors will work with Marlon to come up with a final proposal for the TC.

**Comment by jordan2175** [comment]
I have made changes in section 4.3 to address this.
