### ISSUE TITLE
Change the DNS SVR TAXII service name from taxii to _taxii (or possibly _taxii2?)

### ISSUE THREAD

**Issue by cricard** [oasis-tcs/cti-taxii2#67]
Section 3.8 of the TAXII Version 2.1 - WD01 states 

> Organizations that choose to implement a DNS SRV record in their DNS server to advertise the location of their TAXII Server MUST use the service name taxii.

The example provided, and all the examples I could find, the service name always starts with an underscore (i.e., _taxii).  It also appears that RFC2782 specifies that an underscore should be used.

> Service
        The symbolic name of the desired service, as defined in Assigned
        Numbers [STD 2] or locally.  An underscore (_) is prepended to
        the service identifier to avoid collisions with DNS labels that
        occur in nature.

I propose changing the text to read:

> Organizations that choose to implement a DNS SRV record in their DNS server to advertise the location of their TAXII Server MUST use the service name _taxii.

While I'm thinking about it, are there any concerns over conflicts with anyone who might be leveraging DNS SVR for TAXII1.x, that would make it better to use _taxii2?  (Similar to the concern about using the /taxii/ discovery endpoint)

**Comment by jordan2175** [comment]
We talked about this on the call on 2018-05-15 and the consensus on the call was to accept this change. However, how it is written in the spec is correct.  What we need to do is add some clarifying text from the RFC to make this more clear. John-Mark is going to provide some suggested text.

**Comment by jmgnc** [comment]
added suggested text.  Also, realized that we didn't have proto defined in the text.  I added text saying it MUST be tcp, as I don't think we want to support HTTP over udp (nor would our requests likely fit in it reliably).

**Comment by jordan2175** [comment]
In section 3.8, the text now reads

> Organizations that choose to implement a DNS SRV record in their DNS server to advertise the location of their TAXII Server MUST use the service name taxii2. As defined in [RFC2782], the service name is defined without an underscore, and an underscore is added to construct the correct name in the actual DNS SRV record. The protocol  for this DNS SRV record MUST be tcp.

It is important to note that the name also changed from taxii to taxii2
