### ISSUE TITLE
Document Feedback: Section 3.2 Custom Headers

### ISSUE THREAD

**Issue by emmanvg** [oasis-tcs/cti-taxii2#73]
Apologize for the lack of a better title. Currently, the document states `X-TAXII-Date-Added-First`  and `X-TAXII-Date-Added-Last` as MUST  requirements for three endpoints.

First, none of the examples reflect the use of these Headers. Affects examples in sections:
- 5.3 Get Objects
- 5.5 Get an Object
- 5.6.1 Get Object Manifest

Second, should we take out the 206 portion since we do not have pagination support? Affects section:
- 3.2 Custom Headers

**Comment by jordan2175** [comment]
I changed the 206 text from:

> All HTTP 200 and 206 responses to the following endpoints MUST include the 

to:

> All HTTP 200 series responses to the following endpoints MUST include the

**Comment by jordan2175** [comment]
I added the headers to the three examples, where this is needed.  The examples now look like:

> GET Response
> HTTP/1.1 200 OK
> Content-Type: application/taxii+json;version=2.1
> X-TAXII-Date-Added-First: 2018-05-12T03:05:09.15811Z 
> X-TAXII-Date-Added-Last: 2018-05-12T03:05:17.275544Z
