### ISSUE TITLE
Remove spaces in media types before version parameter

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#74]
In the document we have the media types represented like this, for readability 
"application/taxii+json; version=2.1". However, most browsers and clients do not put any spaces between the options.  We should remove the spaces from the examples so as to not confuse people.

**Comment by jordan2175** [comment]
I removed the space in all of the examples for the media types.  They used to be "application/taxii+json; version=2.1", they are now "application/taxii+json;version=2.1"

**Comment by robincover** [comment]
Noted here, in view of two pending IANA registration requests (SPACE in both examples as submitted)

For STIX: https://www.ietf.org/mail-archive/web/media-types/current/msg00974.html

Optional parameters: version.  This parameter is used to designate
the specification version of STIX that is being used during HTTP
content negotiation. Example: "application/stix+json; version=2.1"
