### ISSUE TITLE
Add some HTTP error codes to POST endpoint

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#75]
We should probably add some more common HTTP error codes POST endpoints.

**Comment by varnerac** [comment]
* 403: Attempt to write to a collection where `can_write` returns `false
* 404: API Root and/or Collection aren't available
* 413: POSTed Payload exceeds `max_content_length` of API Root
* 415: Attempt to POST objects with a content type the server does not support

**Comment by jordan2175** [comment]
The errors code for a POST are now defined as:


> 202 - The request was successful accepted
>
> 401 - The client needs to authenticate.
> 
> 403 - The client does not have access to write to this resource.
> 
> 404 - The client can not write to this resource or it is not available.
> 
> 413 - The POSTed payload exceeds the max_content_length of the API Root.
> 
> 415 - The client attempted to POST a payload with a content type the server does not support.
> 
> 422 - The object type or version is not supported or could not be processed. This can happen, for example, when sending a version of STIX that this TAXII Server does not support and cannot process, when sending a malformed body, or other unprocessable content.
