### ISSUE TITLE
Need server implementation section

### ISSUE THREAD

**Issue by allant0** [oasis-tcs/cti-taxii2#76]
To help taxii server implementation consider all best practices.

a) Create a new section for best practices.
b) Add sections as necessary going forward to include 
- configuration
- object lifecyle
- security considerations

For configuration:
1) TAXII server should consider supporting separate collections for reading vs writing. A common use case for many intelligence organizations is to receive unvetted intelligence data on a read-only collection and then subsequently posting the vetted intelligence data on a separate write-only collection. Therefore TAXII server should not always assume that all collections are read & write.

For object lifecycle:
1) "There are no requirements defined on how long a TAXII server stores a specific object within a collection after it has been successfully posted to a TAXII collection. If the TAXII server needs to remove a STIX object from a collection or wishes to store an object or previous versions is entirely up to the software and the use cases it supports.”

For security considerations:
1) It is recommended that all TAXXII server authenticate and authorize access to collection data on a per-client basis using robust security methods including the mandatory authentication defined in this specification of HTTP Basic Authentication. More advanced security authentication methods are recommended where those products require stronger authentication and authorization frameworks for accessing or posting data to the TAXII server.

**Comment by jordan2175** [comment]
I tweaked some of the text slightly.  

> Server Implementation Considerations
> Configuration
> TAXII servers can support separate collections for reading and writing. A common use case for many intelligence organizations is to receive unvetted intelligence data on a read-only collection and then subsequently posting the vetted intelligence data on a separate write-only collection. Therefore TAXII servers should not always assume that all collections are read & write.
> 
> Object Lifecycle
> There are no requirements defined on how long a TAXII server needs to store a specific object on the server or within a collection after it has been successfully posted to a TAXII collection. If the TAXII server needs to remove an object or a version of the object from the server or collection or it wishes to store an object or previous versions that is entirely up to the software and the use cases it supports.
> 
> Security Considerations
> It is recommended that all TAXII server authenticate and authorize access to collection data on a per-client basis using robust security methods. While this specification defines HTTP Basic as a base level suggested authentication mechanism, more advanced security authentication methods are recommended where those products require stronger authentication and authorization frameworks for accessing or posting data to the TAXII server.

**Comment by jordan2175** [comment]
After talking with Drew, we decided to not include the Configuration section as we felt that it would be very confusing to people.  We also moved this to the Appendix.
