### ISSUE TITLE
Clarify STIX Object versions across multiple Collections

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#77]
I want to clarify my understanding of how STIX Object versions are stored in TAXII.

STIX Objects consist of one or more Object versions. Clients `POST` STIX Object versions to `<api-root>/collections/<id>/objects/` in STIX Bundles.
  
A STIX Object, which consists of one or more Object versions, is uniquely identified by its `id`. Thus, if the same Object is published to Collection 1 and Collection 2, it's still the same Object in STIX.

Currently, my persistence layer ties an Object `id` to one or more Collection `id`s.

I developed this schema because there is only one Object (which is a list of versions) in the universe. If a new version of the Object is pushed to Collection 1, that same version should appear in Collection 2. They are the same object. The same would apply to a version update that revokes the Object.

There is another interpretation of the data model. If I publish an Object version 1 to Collection 1 and Object versions 1 & 2 to Collection 2, am I telling the TAXII server that only clients with read access to Collection 2 can see Object version 2? The STIX Object itself still has 2 versions. I, as the publisher, have made a conscious decision to omit Object version 2 from clients of Collection 1. If I wanted clients of Collection 1 to see Object version 2, I would have published it there. This suggests a schema where Object versions are tied to Collection `id`s.

I honestly don't know which one is right. I think I do for a while, think about it and get confused again.

**Comment by allant0** [comment]
An object version is not tied to where it is stored in one or more collection. A version of object is a historical tracking of changes to that object whether its in 1 collection or 10 collections. 

Most systems will ask for the most recent version of an object and not care to ask for different versions. They will ask for 'the' object and then if they care about the version then they will handle the different notifications/delta UI ...etc updates that they want to do. 

Most publishers will post the latest version of the object only to the taxii server. They wont care whether the taxii server had previous versions and would expect that most systems pulling those objects will get the latest one. If a taxii server keeps multiple versions of an object in a collection then thats a choice of the server. But frankly I think it overcomplicates the server and unnecessary as historical context is not something the taxii server should have to deal with. Thats a product problem and use case specific.
