### ISSUE TITLE
max_content_length example value is not exemplary

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#8]
Section 4.2.1

The max_content_length on the API Root resource needs some clarifying text about what this field is and how to compute it.  Maybe an example or two for "common" possible values.  In addition to this the example has a fake value that we picked out of thin air as a place holder and never went and updated.  The example of 9765625 would equal 9.313MB

**Comment by MarkDavidson** [comment]
Recommendation: change the value to 10485760, which is 10MB, add clarifying text

**Comment by MarkDavidson** [comment]
Consensus is to change value. Proposal with the most consensus was 100mb.

**Comment by jordan2175** [comment]
Added text in 4.2.1 and fixed the example.  Please review.
