### ISSUE TITLE
Custom STIX Property Length Limits

### ISSUE THREAD

**Issue by ikiril01** [oasis-tcs/cti-taxii2#80]
There's been some confusion as to the length limits for custom STIX properties. Apparently there used to be an old SHOULD requirement that custom properties are no longer than 30 characters; however, the only limit currently defined is a hard MUST that custom properties are no longer than 250 characters, which is what we should be conforming to.

Relevant part of STIX 2.0: https://docs.google.com/document/d/1dIrh1Lp3KAjEMm8o2VzAmuV0Peu-jt9aAh1IHrjAroM/edit#heading=h.3a2x3jdr23tq

**Comment by jordan2175** [comment]
We need to make this section in TAXII be the same as STIX.

**Comment by jordan2175** [comment]
Section 7.1.1 now matches the corresponding section in STIX. 

> A TAXII resource MAY have any number of Custom Properties.
> Custom Property names MUST be in ASCII and MUST only contain the characters a–z (lowercase ASCII), 0–9, and underscore (_).
> Custom Property names SHOULD start with “x_” followed by a source unique identifier (such as a domain name with dots replaced by underscores), an underscore and then the name. For example, x_example_com_customfield. 
> Custom Property names MUST have a minimum length of 3 ASCII characters.
> Custom Property names MUST be no longer than 250 ASCII characters in length.
> Custom Property names that are not prefixed with “x_” may be used in a future version of the specification for a different meaning. If compatibility with future versions of this specification is required, the “x_” prefix MUST be used.
> Custom Properties SHOULD only be used when there are no existing properties defined by the TAXII specification that fulfill that need.
