### ISSUE TITLE
Add 501 Not Implemented Status to certain endpoints

### ISSUE THREAD

**Issue by varnerac** [oasis-tcs/cti-taxii2#81]
For TAXII Feed personas (TXF), we can expect that they will allow clients to `GET` objects, but not `POST` them. We need a predictable way for TAXII Feeds to indicate that they don't implement the full range of TAXII Endpoints.

I propose that TAXII feeds MUST return HTTP status code 501,  "Not Implemented" if they don't implement:

* Add Objects
* Delete Object

I don't know that we've enumerated which endpoints a TXF MUST or SHOULD implement.

**Comment by jordan2175** [comment]
In addition to this, the spec actually allows a TAXII server to not use collections at all or channels at all.  So this error code probably needs to be in a few other places as well.

**Comment by JasonKeirstead** [comment]
Isn't this already covered by having read-only collections?

**Comment by jordan2175** [comment]
So if your server is just a discovery server and offers no API-Roots, then you probably need this on /{api-root}/.  If you have turned off all collections and are only using channels (once we add them) then you will probably want this on /{api-root}/channels/ as well????

**Comment by johnwunder** [comment]
I get what you're asking for with this request and I think it makes sense, but I'm not sure 501 is the right error code. 501 says that "the server does not recognize the request method and is not capable of supporting it for any resource." The **for any resource** there makes me think there's a better error code to use. 405 seems more appropriate, though note the requirement that you return a list of methods that are acceptable for that resource.

**Comment by varnerac** [comment]
Yeah, you're right. 501 is definitely not it. Didn't notice that it's particular to the method. 405 does seem better but would add the `Allow:` header requirement to the response. Not sure if it's worth the hassle. Maybe leaving it 403 is fine. The 405 seems clearer. The fact that it's cacheable also fits better.

**Comment by allant0** [comment]
I disagree that 501/not implemented is returned. Not authorized is fine. In some cases, a taxii server will look like a TXF to a client because that client is not authorized to post data either at all or to a certain collection. For other clients they may be allowed. Therefore, introducing not implemented is not required because it could be credential based whether you look like a TXF or TXS.

**Comment by jordan2175** [comment]
What about a TAXII Server that does not support Collections at a all, and only supports channels?

**Comment by jmgnc** [comment]
yeah 403/404/405 is a better option...  IMO the return code for not allowed at all should be the same for not implemented...  reason for this is to prevent leakage of information...  if we have a read-only collection that returns 405, but another collection that is read-write, but returns 403, this lets an attacker not that they might be able to succeed by finding credentials and be successful in attacking a collection...  (this is the same thing about base username vs bad password, and why you give the same response to both these days)...

**Comment by JasonKeirstead** [comment]
I still do not understand the end-to-end of why this is needed. What is a client going to do differently with a 405 error code vs a 403 ? ( We already return 403 for this if you try to GET a write-only collection, or try to POST to a read-only collection ).

Following the KISS principle I am still not sure why any of this needs to be done.

**Comment by allant0** [comment]
Currently there is no spec for channels and i think we should reserve solving the channel problem when we have a spec for it. personally i think a server will always support both collections and channels.
