### ISSUE TITLE
Add clarifying text if no collections are returned or collections are not enabled

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#83]
We need to add some clarifying text to the spec to make sure servers respond correctly.  The two examples use cases are:

1) You get the collections endpoint and no collections are returned 
2) The collections feature has been turned off or is not enabled

The consensus on Slack is that the server should return an empty set.

**Comment by varnerac** [comment]
Just to clarify, do you mean return an empty object `{}`, not an empty `[]` for `collections`. `collections` is a `list` and TAXII 2 lists cannot be empty.

I think the existing text adequately covers issue 1:

> If there are no Collections in the list, this key MUST be omitted and the response is an empty object.

I don't know that we have a profile for a TAXII server that doesn't serve collections yet.

**Comment by jordan2175** [comment]
Yeah, after looking at this again, I believe we have already fixed this in a previous WD and just did not close the issue.
