### ISSUE TITLE
Get STIX Object by ID does not describe why a bundle is required

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#9]
We should add some clarifying text around why a bundle is needed for get an object by ID.  The reason is that you might get more than one version of the STIX object.

**Comment by MarkDavidson** [comment]
Recommendation: Add clarifying text

**Comment by MarkDavidson** [comment]
Object may have an embedded object, which is another reason why a bundle would be used (per Allan Thomson)

**Comment by MarkDavidson** [comment]
Consensus is to add clarifying text, text is TBD

**Comment by jordan2175** [comment]
I added some clarifying text in section 5.3
