### ISSUE TITLE
Make the TAXII Envelope contain a list of objects not a bundle

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#97]
The consensus in the group is to change the TAXII Envelope from having a data property that contains a STIX bundle to having an objects property that just contains a list of STIX objects. This will be done in WD06. This issue is just for documentation purposes.

**Comment by StephenOTT** [comment]
As a reference would be good to have a additional query param or endpoint that provides the client with a Bundle version of the objects.

**Comment by jordan2175** [comment]
This was changed for WD06 based on TC working call consensus and review and acceptance on the full TC call today, 2019-01-17
